use_frameworks!

platform :ios, '9.0'

target 'FBPickerView_Example' do
  pod 'FBPickerView', :path => '../'

  target 'FBPickerView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
